### ISSUE TITLE
GPT 遇到频率限制时 自动重试

### ISSUE THREAD

**Issue by Anthony-Hoo** [CSUSTers/csust-got#191]
配置文件增加一个字段 `chatgpt.retry_num` 默认为5次，即在遇到频率限制时自动重试五次。

> _五五五五wu~_

**Comment by icceey** [comment]
是不是可以关了

**Comment by Anthony-Hoo** [comment]
> 是不是可以关了

@icceey 还没好吧，有时候还是会超时
