### ISSUE TITLE
[BUG] Message count command missing messages after group name be changed

### ISSUE THREAD

**Issue by Anthony-Hoo** [CSUSTers/csust-got#196]
<img width="940" alt="image" src="https://user-images.githubusercontent.com/30752208/233008839-8a6457b2-43a6-453a-a453-2c25c3b4fa8c.png">

group name : "Rachel's Backyard" -> "Rachel's 夸夸群"

@Rachel030219 可以先看看这个修复下，比较简单捏

**Comment by Rachel030219** [comment]
fixed in commit a798352
