### ISSUE TITLE
如果支持 URL shortener 就好了。

### ISSUE THREAD

**Issue by YuJuncen** [CSUSTers/csust-got#3]
```
> /shorten_url "vosouth.net"
< 短链接完成啦！你可以在 abc.xyz/xxxxxx 访问！
```
大概就这种感觉……？

**Comment by icceey** [comment]
还有长链接

**Comment by icceey** [comment]
最好是回复某条包含链接的消息也可以用

**Comment by YuJuncen** [comment]
> 还有长链接

棒欸！

**Comment by hugefiver** [comment]
感觉在 inline 模式做是不是好点

**Comment by Anthony-Hoo** [comment]
> ```
> > /shorten_url "vosouth.net"
> < 短链接完成啦！你可以在 abc.xyz/xxxxxx 访问！
> ```
> 
> 大概就这种感觉……？

@YuJuncen 

<img width="193" alt="image" src="https://user-images.githubusercontent.com/30752208/233911054-6dc9a66f-13e3-4736-a034-69fd48106b61.png">

该白嫖 GitHub 服务器资源了，使用这个库实现 [Anthony-Hoo/hugeURLer](https://github.com/Anthony-Hoo/hugeURLer)

**Comment by YuJuncen** [comment]
噫，好，老嚯做了！
