### ISSUE TITLE
[feature] inline mode drop all tracing parameters from URL

### ISSUE THREAD

**Issue by hugefiver** [CSUSTers/csust-got#321]
- [x] 使用inline模式，替换文本中出现的URL为无跟踪的URL
- - [x] Bilibili (链接/短链接)
- - [x] Google/Bing... Search
- - [x] 知乎
- [x] 将Twitter(X)链接替换为 fxtwitter

需要更多功能请添加在该issue或在下方留言

**Comment by Anthony-Hoo** [comment]
要做bilibili的吗，还有别的？

**Comment by hugefiver** [comment]
> 要做bilibili的吗，还有别的？

先做阿B的吧

以后可以加短链接功能

**Comment by Anthony-Hoo** [comment]
> > 要做bilibili的吗，还有别的？
> 
> 先做阿B的吧
> 
> 以后可以加短链接功能

只有一个bot怎么用inline同时实现短链接和无追踪啊

**Comment by hugefiver** [comment]
> > > 要做bilibili的吗，还有别的？
> > 
> > 
> > 先做阿B的吧
> > 以后可以加短链接功能
> 
> 只有一个bot怎么用inline同时实现短链接和无追踪啊

一起加
