### ISSUE TITLE
[feature] 再mc自杀

### ISSUE THREAD

**Issue by hugefiver** [CSUSTers/csust-got#336]
0. yan说『再mc自杀』。
1. 当群组中累计使用2次`/mc`命令时，bot就会『自杀』不再响应群组中的消息。
2. 群组中任意人使用`/reburn`对bot使用『大复活术』，当然是需要『祭品』的。
3. 当bot『复活』时，第一次和第二次使用`/mc`命令的人需要分别『奉献』1分钟和5分钟的生命，即被ban（如果是管理员则是被kill）。如果是同一个人则累加在一起。
4. 使用`/reburn`的人下一次『奉献』的『祭品』翻倍。

## bug
- [x] #416

**Comment by icceey** [comment]
策划给你你来当
