### ISSUE TITLE
[feature request] Longwang

### ISSUE THREAD

**Issue by hugefiver** [CSUSTers/csust-got#6]
每日 00:00 统计前一天发言情况，分析以下数据并生成图表：

- 总消息数，与上期活跃度变化情况
- 所有消息中，纯文本、图片、贴纸等的比例
- 群成员活跃度前 5 的用户
- 各时段群成员活跃度情况，与上期的变化情况

> 由某Q启发

**Comment by YuJuncen** [comment]
那么，这个功能就由今天的龙王负责开发吧！

**Comment by icceey** [comment]
Development goals at this stage

- [ ] Record the users who send the most messages per day.
- [ ] Considering that there are not many picture messages, no additional statistics are performed on the pictures, only the number of Stickers is extra calculated.
- [ ] Bot's commands are not counted.
- [ ] Only top three are reported.

**Comment by icceey** [comment]
Complete by grafana
